### ISSUE TITLE
Mysql database integration

### ISSUE THREAD

**Issue by paulharman** [brandonshults/pipoam#1]
Please could you try to integrate this with the mysql database?

**Comment by brandonshults** [comment]
Yes, but what do you want to integrate exactly?

**Comment by paulharman** [comment]
The ideal option for me would be able to point this tool at the db, use multiple polygons to create the desired areas and then delete the other unwanted  entries.

**Comment by brandonshults** [comment]
I've implemented loading points from databases, but I am hesitant to add a tool that destroys points.  I will have to give this idea more thought.

**Comment by brandonshults** [comment]
After careful consideration I have decided that pruning pogom databases is outside of the scope of this project.  I'm sorry to disappoint.
