### ISSUE TITLE
load multiple files

### ISSUE THREAD

**Issue by Jasonhcwong** [brandonshults/pipoam#5]
Hi, it will be nice to be able to load multiple spawnpoint files.
Useful when merging several smaller maps into a single map and when re-partition a city which is consist of multiple smaller maps.
It will be even nicer if pipoam can perform deduplication when loading multiple files.

**Comment by brandonshults** [comment]
I've added the ability to merge points from a file or from a database.  The merge will, indeed, throw out exact duplicate points.
