### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by ObviousLeeGitHub** [brandonshults/pipoam#8]
nvm

**Comment by jRam84** [comment]
How did you fix this issue? I can't load the spawns either.

**Comment by ObviousLeeGitHub** [comment]
My file had multiple objects: "spawns", "emptylocs", "gyms", etc.. Basically you only need one object with spawns in it and each spawn must have a lat and a lng property.. Any additional properties doesn't matter. Look at the example.json
